# Generated by Django 5.2.11 on 2026-03-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_otplog_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='lms.course'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='lms.plan'),
        ),
    ]
